INHERIT: ./docs/env

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest 
  icon: 
    repo: fontawesome/brands/git

plugins:
  - macros
  - search
  - mike
  - with-pdf:
      exclude_pages:
        - 'informations'
      toc_level: 1
      cover_subtitle: Indiquer ici le sous-titre du rapport
      cover_logo: ./docs/logo.png
      toc_title: Table des matières
      output_path: ../Documentation.pdf